#cloud-config
users:
  - name: gaidar
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${vms_ssh_root_key}
package_update: true
package_upgrade: false
packages:
  - vim
  - wget
  - snapd
runcmd:
  - mkdir -p /home/gaidar/.kube
  - snap install microk8s --classic
  - usermod -a -G microk8s gaidar
  - chown -f -R gaidar /home/gaidar/.kube
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - mv ./kubectl /usr/local/bin/kubectl