#cloud-config
users:
  - name: gaidar
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${vms_ssh_root_key}
package_update: true
package_upgrade: false
packages:
  - vim
  - wget
  - snapd
runcmd:
  - mkdir -p /home/gaidar/.kube
  - snap install microk8s --classic
  - usermod -a -G microk8s gaidar
  - chown -f -R gaidar /home/gaidar/.kube
  - sleep 5m
  - microk8s enable ingress

# microk8s config
# sed -i '/IP\.2 = [0-9.]\+/a IP.3 = '$(wget -O - -q icanhazip.com)'' /var/snap/microk8s/current/certs/csr.conf.template
# sudo microk8s refresh-certs --cert front-proxy-client.crt

# ssh $(terraform output -json vm_details | jq -r '.[0].ip_address') "microk8s config" | sed "s|    server: https://.*|    server: https://$(terraform output -json vm_details | jq -r '.[0].ip_address'):16443|" > ~/.kube/config