#cloud-config
users:
  - name: gaidar
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${vms_ssh_root_key}
package_update: true
package_upgrade: false
packages:
  - vim
  - wget
  - snapd
runcmd:
  - snap install microk8s --classic
  - usermod -a -G microk8s gaidar
  - chown -f -R gaidar /home/gaidar/.kube
